---
env:
  ART_GROUP: spring
  APP_NAME: springboot

profiles:
  - name: quarkus
    description: builds the quarkus utility package library
    type: lib/quarkus
    target: quarkus
    
  - name: spring-boot
    description: builds the spring-boot utility package library
    type: lib/spring-boot
    target: spring-boot
functions:
  - name: build-spring-boot-pkg
    description: build artisan package for spring app
    run:
      - art build -t ${ART_REG}/${ART_GROUP}/${APP_NAME} -p spring-boot
      - art push ${ART_REG}/${ART_GROUP}/${APP_NAME}:latest
...
